name: Honey's Place Inventory Sync

on:
  schedule:
    - cron: '0 3 * * *'  # daily at 3:00 AM UTC
  workflow_dispatch:

jobs:
  run-inventory-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Debug - Test API connectivity
        run: |
          echo "🔍 Testing Honey's Place API connectivity..."
          curl -I -u "${{ secrets.HP_USERNAME }}:${{ secrets.HP_PASSWORD }}" https://honeysplace.com/API/inventory/index.php

      - name: Debug - Download XML for inspection
        run: |
          curl -u "${{ secrets.HP_USERNAME }}:${{ secrets.HP_PASSWORD }}" https://honeysplace.com/API/inventory/index.php -o honeysplace_inventory.xml
          echo "✅ XML downloaded to honeysplace_inventory.xml"

      - name: Upload downloaded XML
        uses: actions/upload-artifact@v4
        with:
          name: honeysplace-raw-xml
          path: honeysplace_inventory.xml

      - name: Run PHP script
        env:
          HP_USERNAME: ${{ secrets.HP_USERNAME }}
          HP_PASSWORD: ${{ secrets.HP_PASSWORD }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_PASSWORD: ${{ secrets.SHOPIFY_API_PASSWORD }}
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
          SYNC_NOTIFICATION_EMAIL: ${{ secrets.SYNC_NOTIFICATION_EMAIL }}
        run: php update_inventory.php

      - name: List files for debugging
        run: ls -alh

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: inventory-sync-log
          path: inventory_sync_log.txt
