name: Sync Honey's Place Inventory

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-inventory:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧰 Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: ✅ Verify Inventory URL Reachable
        run: |
          echo "Checking URL..."
          curl -I --fail https://www.honeysplace.com/df/IGnJiYVwz6xVfAaR/xml

      - name: 🚀 Run PHP script
        run: php update_inventory.php

      - name: 📤 Upload Log File
        uses: actions/upload-artifact@v4
        with:
          name: inventory-log
          path: inventory_sync_log.txt
