name: Honey's Place Inventory Sync

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  sync-inventory:
    runs-on: ubuntu-latest
    env:
      SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
      SHOPIFY_API_PASSWORD: ${{ secrets.SHOPIFY_API_PASSWORD }}
      SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run inventory sync script
        run: php update_inventory.php

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: inventory-log
          path: inventory_sync_log.txt
